---
- name: "Provisioning des outils DevSecOps"
  hosts: localhost
  connection: local
  become: yes

  vars:
    ansible_python_interpreter: /usr/bin/python3
    kubectl_version: "v1.31.0"
    sonar_version: "6.2.1.4610"

  roles:
    - java_setup   
    - kubernetes
    - helm
    - sonarqube
